import { addOpacityListenersExp } from "./hover_function.js";
addOpacityListenersExp("IHM")
addOpacityListenersExp("weatherapp")
addOpacityListenersExp("danmashi")
addOpacityListenersExp("appOsyris")
addOpacityListenersExp("dashboard")
addOpacityListenersExp("flipper")
addOpacityListenersExp("escape")
addOpacityListenersExp("endless")

addOpacityListenersExp("domolabo")
addOpacityListenersExp("coffre")
addOpacityListenersExp("marcus")
addOpacityListenersExp("robolympiades")
addOpacityListenersExp("assistant")
addOpacityListenersExp("mecanum")
addOpacityListenersExp("bb8")
addOpacityListenersExp("moduleESP")
addOpacityListenersExp("bluetooth")